### ISSUE TITLE
Parser does not require well-formed XML document

### ISSUE THREAD

**Issue by simonrozsival** [segmentio/xml-parser#18]
This snippet: <A><B></A></B> is parsed without any warning - is it a bug or a feature?

**Comment by mk-pmb** [comment]
#### Welcome to GitHub!

Comments here support some HTML formatting as part of [GitHub-flavored Markdown](https://guides.github.com/features/mastering-markdown/). If you want the code to show up as code, you'll have to wrap it into code quotes (<code>`…`</code>): `<b></b>` or a code block, best with syntax highlight:

<pre>```html
&lt;b&gt;&lt;/b&gt;
```‍</pre>

Then it will show up as:

``` html
<b></b>
```

## Parser behavior

To my understanding of the readme, being able to parse your example code is a core feature of this parser, described by the author as "Simple non-comp[l]iant".
Its lack of care for XML compliance makes it easy to use in situations where a real XML parser would require you to fix the input file first.
